### ISSUE TITLE
Search API endpoint and search results page

### ISSUE THREAD

**Issue by chrisgrieser** [aelew/devterms#10]
Just stumbled upon your project, nicely done!

I was happy to see you already got an API. Would it be possible to add a search request? Something like: `https://devterms.io/api/v1/define?search=`, resulting in a list of terms matching the query.

Similarly, it is common to add browser searches via Urls with a query parameter, e.g. `https://devterms.io/search?q=`. Such a search functionality would be nice to directly get to a term.

**Comment by aelew** [comment]
I'll be adding a search API endpoint soon!
As for browser searches, do you have any ideas for search page design in mind?

**Comment by aelew** [comment]
> Not really, no, not much of a design person. :S I could just say that keyboard-navigation of the search results and small preview text would be useful

I'll make sure to keep this in mind :)

**Comment by aelew** [comment]
Search API endpoint added in f521f03, let me know if you encounter any issues 🙂
I'll also make the /define endpoint accept an ID soon

**Comment by chrisgrieser** [comment]
Nice, works as expected! May I ask what the `page RegExp` is supposed to do?

**Comment by chrisgrieser** [comment]
btw, here is the result, an Alfred integration of devterms.
![Pasted image 2024-03-02 at 11 22 40@2x](https://github.com/aelew/devterms/assets/73286100/8d63e36c-2dcc-4cfc-838d-438e79fd56ee)

I bundled it with a bunch of other development searcher in this [Alfred plugin](https://alfred.app/workflows/chrisgrieser/search-all-the-docs/) (not live yet, since the Alfred team reviews all changes before they gove live)

**Comment by aelew** [comment]
> Nice, works as expected! May I ask what the `page RegExp` is supposed to do?

It's really just the page number. I had to [use some regex for schema validation](https://github.com/aelew/devterms/blob/main/src/app/api/%5B%5B...slugs%5D%5D/public.ts#L47) because query params are strings in Elysia and I'm not sure how to convert strings into numbers using TypeBox. I'll look into this again later though

> btw, here is the result, an Alfred integration of devterms. ![Pasted image 2024-03-02 at 11 22 40@2x](https://private-user-images.githubusercontent.com/73286100/309466816-8d63e36c-2dcc-4cfc-838d-438e79fd56ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MTAxMzUsIm5iZiI6MTcwOTQwOTgzNSwicGF0aCI6Ii83MzI4NjEwMC8zMDk0NjY4MTYtOGQ2M2UzNmMtMmRjYy00Y2ZjLTgzOGQtNDM4ZTc5ZmQ1NmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDIwMDM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZTg2YTExZTljNWZiNzRjNjQ4ODE1MDAzZjVkYzljNTQyYzU2OTU4Y2UxNmJiNGQ0M2JiOGE4YmU2M2UxMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0fuBT0KXDip_FZ9S8GlfJApDMjB2LwR_yUB935bkA0A)
> 
> I bundled it with a bunch of other development searcher in this [Alfred plugin](https://alfred.app/workflows/chrisgrieser/search-all-the-docs/) (not live yet, since the Alfred team reviews all changes before they gove live)

This is pretty cool! I use Raycast myself, but it's nice to see DevTerms being used in a third-party tool for the first time. One thing I would like to say is I would recommend [converting the term to a slug](https://github.com/aelew/devterms/blob/250031b7f232abf7c9c3a50180c1e08e9da13495/src/lib/utils.ts#L23C17-L23C27) in the URL to avoid any unexpected issues. I just pushed a commit that adds `url` to every hit in the search endpoint response, so you could use that as well :)

**Comment by aelew** [comment]
Page number validation no longer uses regex and the /define endpoint now accepts definition IDs as well!
